name: New Contribution
description: Register a new contribution.
labels: ["new-contribution"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your new contribution to Processing.
        
        Please provide the URL to the library properties text file. 
        For example, in your library release artifacts, if your library is called my_library, the file might be called my_library.txt.
  - type: input
    id: url
    attributes:
      label: properties_url
      description: URL of your properties text file, in your published release artifacts.
      placeholder: https://
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Also provide the type of contribution. The allowed values are `library`, `examples`, `tool` or `mode`.
  - type: dropdown
    id: contribution_type
    attributes:
      label: contribution_type
      description: The type of contribution.
      options:
        - library
        - examples
        - tool
        - mode
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Once you submit this form, the properties file found at the url will be parsed and validated. 
        
        The result of this validation will be added to this issue:
        * If the text file is valid, a pull request will be automatically created, adding your contribution to the repository. 
        * If the text file is not valid, a comment with the error will be added to the issue. You will need to edit your properties file before the contribution can be added.
