name: 👗 New Mode
description: Submit a new Processing mode
labels: ["new contribution", "mode"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution to Processing!

        Modes, also called language modes, allow Processing users to code and run sketches in different code languages and on different platforms ([read more](https://github.com/processing/processing/wiki/Mode-Overview)).

        If you need help creating a mode, see the [Mode Overview](https://github.com/processing/processing/wiki/Mode-Overview) or ask on the [Processing Forum](https://discourse.processing.org/).

        Please provide the necessary information below.

        ---

        #### About the Properties File

        A properties file (e.g., `myMode.txt`) is necessary for submitting your mode. It should be a direct copy of your `mode.properties` file, hosted in the same directory as your `.zip` distribution, and share the same base name.

        **Example:**
        If your release artifacts are hosted at `https://github.com/yourusername/yourrepo/releases/latest/`, ensure these files are available:
        - `.txt` file: `https://github.com/yourusername/yourrepo/releases/latest/download/myMode.txt`
        - `.zip` file: `https://github.com/yourusername/yourrepo/releases/latest/download/myMode.zip`

        > [!IMPORTANT]
        > Make sure to keep the same URL in the future. If you release a new version, the URL should remain the same.

        ---
  - type: input
    id: properties_url
    attributes:
      label: Properties File URL
      description: URL of your properties `.txt` file (e.g. `myMode.txt`).
      placeholder: https://
    validations:
      required: true
  - type: input
    id: documentation_url
    attributes:
      label: Home Page URL
      description: URL of the home page for your mode.
      placeholder: https://
    validations:
      required: true
  - type: checkboxes
    id: guidelines_confirmation
    attributes:
      label: Guidelines Confirmation
      description: All modes must follow the guidelines described on the [Mode Overview](https://github.com/processing/processing/wiki/Mode-Overview) page.
      options:
        - label: I confirm that my mode follows the guidelines.
          required: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        Once you submit this form, the `.txt` file at the provided URL will be parsed and validated.

        The result of this validation will be added to this issue:
        - If valid, a pull request will automatically be created to add your mode to the repository.
        - If invalid, a comment will be added with details of the error. You will need to fix the file and resubmit.
        
        ---
  - type: input
    id: remarks
    attributes:
      label: Additional Remarks
      description: Anything else you'd like to mention about your submission - any comments or questions.
      placeholder: Tell us any other information or questions about your submission
